### ISSUE TITLE
Angular 5.2.x compatibility

### ISSUE THREAD

**Issue by tamascsaba** [code-orange/telemachy#1]
Use [ng-packgr](https://github.com/dherges/ng-packagr) to package the module, becsese I got typescript error like:
```telemachy/src/telemachy.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.```

**Comment by timvdalen** [comment]
Thanks for your report, I'll look into Angular Package Format to see what I need to change in order to have this work.

Normally, you shouldn't need to compile the library yourself - a compiled version is included with the npm package.
