### ISSUE TITLE
Swapping the default Template

### ISSUE THREAD

**Issue by dmlang** [code-orange/telemachy#3]
Hey, thanks for the great lib! 
I would like to change the template of the TelemachyTourComponent. I tried to extend the class, but its not exported by the TelemachyModule and i don't want to manually alter the lib code. What do you suggest?

Best regards,
Dominik

**Comment by timvdalen** [comment]
Thanks!

Your use-case sounds reasonable, I agree that extending the class is the proper way to go in this case (if you can't do your changes with just CSS).
I think exporting the component from the package is the correct solution here, so I'll look into that.
I think I'll have some time this weekend to do that.

In the meantime, if you'd like to submit a PR, I'd be happy to look over it and merge it.

**Comment by timvdalen** [comment]
Fixed in #4
